<a href="https://www.kaggle.com/code/charlesguthmann/chuck-first-notebook?scriptVersionId=111588564" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/test.csv
/kaggle/input/titanic/gender_submission.csv

In [2]:
train_data = pd.read_csv("/kaggle/input/titanic/train.csv")
test_data = pd.read_csv("/kaggle/input/titanic/test.csv")
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
train_data.info()
#super useful for quickly seeing which columns have null data, for instance
#if we want a less beautiful, more simple version, train_data.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [4]:
train_data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [5]:
num_data = train_data._get_numeric_data().columns
num_data

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [6]:
train_data["Sex"] = train_data["Sex"].astype("category")
train_data["Sex"] = train_data["Sex"].cat.codes
train_data["Sex"].describe()
#64% of the titanic was men
# man == 1

##  _______________________________test data _______________________________________________

test_data["Sex"] = test_data["Sex"].astype("category")
test_data["Sex"] = test_data["Sex"].cat.codes

In [7]:
#make categorical vars
train_data["Pclass"].unique()

train_data["class2"] = [1 if x == 2 else 0 for x in train_data["Pclass"]]
train_data["class3"] = [1 if x == 3 else 0 for x in train_data["Pclass"]]

##  _______________________________test data _______________________________________________

test_data["class2"] = [1 if x == 2 else 0 for x in test_data["Pclass"]]
test_data["class3"] = [1 if x == 3 else 0 for x in test_data["Pclass"]]

In [8]:
## Test data has a single missing fair price, let's fill it with the average. 
test_data.isna().sum()
test_data["Fare"].fillna(14, inplace=True)

In [9]:
#Columns for lin reggresion

independent_vars = ["Sex", "SibSp", "Parch", "Fare", "class2", "class3"]

dependent_var = ["Survived"]

X_train = train_data[independent_vars]
Y_train = train_data[dependent_var]

X_test = test_data[independent_vars]

## Linear Regression

In [10]:
linear_model = LinearRegression()
linear_model.fit(train_data[independent_vars], train_data[dependent_var])
linear_model.predict(test_data[independent_vars]) #if >.5 -> round to 1, else -> round to 0
results = np.round(np.clip(linear_model.predict(test_data[independent_vars]), 0, 1))

## .77 accuracy

## Random Forrest

In [11]:
rf_model = RandomForestClassifier(n_estimators = 100)
rf_model.fit(X_train, Y_train.values.ravel())

RandomForestClassifier()

In [12]:
Y_pred = rf_model.predict(X_test)
rf_pred = list(Y_pred)


rf_submission = test_data[["PassengerId", "Pclass"]]
rf_submission["Survived"] = rf_pred

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [13]:
rf_submission = rf_submission.drop("Pclass", axis = 1)
rf_submission

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [14]:
rf_submission.to_csv("rf_submission_3.csv", index = False)

In [15]:
passenger_list = test_data["PassengerId"].tolist()

In [16]:
test_data["Survived"] = results
submission_data = test_data[["PassengerId", "Survived"]]
submission_data["Survived"]=submission_data["Survived"].astype("int")

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [17]:
submission_data

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [18]:
submission_data.to_csv("submission4.csv", index=False)

In [19]:
import csv
header = ["PassengerId", "Survived"]
rows = [[passenger_list[i], rf_pred[i]] for i in range(len(rf_pred))]



with open("rf_results.csv", "w+") as f:
    writer = csv.writer(f)
    writer.writerow(header)
    writer.writerows(rows)
    
#now with random forrest